import { StyleSheet } from "react-native";

export const Styles = StyleSheet.create({
  container: {
    height: "100%",
    width: "100%",
    backgroundColor: "#FFFFFF",
  },
  picture: {
    marginTop: 40,
    width: 403,
    height: 391,
  },
  title: {
    width: "80%",
    marginTop: 20,
    marginLeft: "10%",
    textAlign: "center",
    fontSize: 33,
    fontWeight: "bold",
    fontFamily: "Helvetica",
    color: "#414242",
  },
  code: {
    marginLeft: "auto",
    marginRight: "auto",
    textAlign: "center",
    letterSpacing: 15,
    fontSize: 33,
    fontWeight: "bold",
    fontFamily: "Helvetica",
    color: "#4369B0",
  },
  card: {
    width: 300,
    paddingTop: 10,
    paddingBottom: 10,
    marginTop: 20,
    marginLeft: "auto",
    marginRight: "auto",
    borderWidth: 1,
    borderRadius: 10,
    borderColor: "gray",
  },
  smallText: {
    width: 350,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 20,
    marginBottom: 22,
    textAlign: "left",
    fontSize: 13,
    fontFamily: "Helvetica-Light",
    color: "#414242",
  },
  smallTextDanger: {
    width: 350,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 10,
    marginBottom: 22,
    textAlign: "left",
    fontSize: 11,
    fontFamily: "Helvetica-Light",
    color: "red",
  },
  topSpace: {
    marginTop: "5%",
  },
});
